version: '3.7'

services:

  remix:
    container_name: remix
    command: remix:dev                
    volumes:
      - .:/usr/src/app
    build:
      context: .
    ports:
      - "3000:3000"

  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - dbvolume:/var/lib/postgresql/data
    env_file: ./.env
    ports:
      - 5432:5432

volumes:
  dbvolume:
